Dig: StreamMonitor Class Reference
StreamMonitor Class Reference
Public Member Functions
StreamMonitor (SpotterParams p)
Subsequence processSample (data_t *sample)
Top-level function to be called at each time step.
void addTemplate (Template const &seq)
Add a traning example.
void addTemplates (std::vector< Template > const &seqs)
Convenience function to call addTemplate() with a number of sequences.
dist_calls_t getDistCallCounts () const
Return the number of calls so far to the core distance-computing subroutine.
tick_t getTime () const
Returns the current time step.
data_t getCutoff ()
Returns the cutoff distance for what counts as a match in the nearest-neighbor searches StreamMonitors use.
void setCutoff (data_t newCutoff)
Sets the cutoff distance for nearest-neighbor searches.
void setMode (StreamMonitorMode mode)
Sets the StreamMonitor's mode (test vs debug; the former breaks unit tests)
void setMaxWarp (steps_t maxWarp)
Sets the maximum amount of time warping to use when computing distances between time series.
std::vector< Subsequence > feedStream (data_t *data, tick_t len)
Returns the events found in the supplied stream of data.
Member Function Documentation
void StreamMonitor::addTemplate (Template const & seq)
Add a traning example.
Parameters:
seq A labeled time series (of the appropriate dimensionality)
References Sequence::data, Template::label, Sequence::nDims, and Sequence::nSamples.
Referenced by addTemplates().
void StreamMonitor::addTemplates (std::vector< Template > const & seqs)
Convenience function to call addTemplate() with a number of sequences.
Parameters:
seqs The time series to be added as traning data
References addTemplate().
std::vector< Subsequence > StreamMonitor::feedStream (data_t * data, tick_t len)
Returns the events found in the supplied stream of data.
Parameters:
data The array of data describing the stream
len The number of samples in the stream; note that for a stream of k dimensions, this means that the array supplied must be of length k*len
Returns:
The collection of non-overlapping matching subsequences ("events"), in chronological order, discovered in the stream.
References Subsequence::isValid(), and processSample().
Subsequence StreamMonitor::processSample (data_t * sample)
Top-level function to be called at each time step.
Parameters:
sample An array of length k corresponding to the latest sample in the k-dimensional stream
References Subsequence::latency, and Subsequence::te.
Referenced by feedStream().
The documentation for this class was generated from the following files:
src/stream/StreamMonitor.hpp
src/stream/StreamMonitor.cpp