Dig: SignalMonitor Class Reference
SignalMonitor Class Reference
Public Member Functions
SignalMonitor (SpotterParams p)
void processSample (data_t *sample)
Top-level function to be called at each time step.
void addTemplate (Template const &seq)
Add a traning example.
void addTemplates (std::vector< Template > const &seqs)
Convenience function to call addTemplate() with a number of sequences.
bool checkSequenceOptimal (Subsequence seq)
Determine whether a sequence being considered as a possible event is the best event that could be found, or whether a better one might be found in a few time steps (or some heuristic for whether this is likely / important).
void onSequenceReported (Subsequence seq)
To be called when a subsequence is reported.
Subsequence getCurrentBestSeq ()
Returns the best sequence found so far but not yet reported.
void setCutoff (data_t newCutoff)
Returns the cutoff distance for nearest-neighbor comparisons.
void setMode (StreamMonitorMode mode)
Sets the SignalMonitor's mode (test vs debug; the former breaks unit tests)
void setMaxWarp (steps_t maxWarp)
Sets the maximum amount of time warping to use when computing distances between time series.
Member Function Documentation
void SignalMonitor::addTemplate (Template const & seq)
Add a traning example.
Parameters:
seq A labeled time series
References Sequence::nSamples, and PatternSpotter::setSameClassMeansOptimal().
Referenced by addTemplates().
void SignalMonitor::addTemplates (std::vector< Template > const & seqs)
Convenience function to call addTemplate() with a number of sequences.
Parameters:
seqs The time series to be added as traning data
References addTemplate().
bool SignalMonitor::checkSequenceOptimal (Subsequence seq)
Determine whether a sequence being considered as a possible event is the best event that could be found, or whether a better one might be found in a few time steps (or some heuristic for whether this is likely / important).
Parameters:
seq The subsequence being considered as a possible event
References Subsequence::dist, and Subsequence::isValid().
void SignalMonitor::onSequenceReported (Subsequence seq)
To be called when a subsequence is reported.
Notifies each PatternMonitor that this is the case via notifySequenceReported() and resets the best sequence found so far to one that doesn't overlap with that reported
References Subsequence::dist.
void SignalMonitor::processSample (data_t * sample)
Top-level function to be called at each time step.
Parameters:
sample A pointer to the latest data point in this signal
References Subsequence::dist.
The documentation for this class was generated from the following files:
src/stream/SignalMonitor.hpp
src/stream/SignalMonitor.cpp